apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: backend-pv-storage
        persistentVolumeClaim:
          claimName: backend-pv-claim
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: node
        image: ${REGISTRY_NAME}/knowzone-backend:${VERSION}
        volumeMounts:
        - mountPath: "/data/upload"
          name: backend-pv-storage
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 2
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-admin-kz-user
              key: connectionString.standardSrv
        - name: REACT_URL
          value: ${FRONTEND_URL}
        - name: PUBLIC_UPLOAD_PATH
          value: /data/upload/public
        - name: IMAGE_UPLOAD_SUBPATH
          value: images
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: knowzone-secret
              key: session-secret
        - name: SESSION_NAME
          value: sid
        - name: SESSION_LIFETIME
          value: "3600000"
        - name: SESSION_SECURE
          value: "false"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ${BACKEND_LB_PREFIX}
  name: backend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: backend
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-zrs
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-zrs
  resources:
    requests:
      storage: 5Gi
