apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "5.0.1"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: kz-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: knowzone-secret
        key: mongo-password
      roles:
        - db: "admin"
          name: "clusterAdmin"
        - db: "admin"
          name: "userAdminAnyDatabase"
        - db: "admin"
          name: "readWrite"
        - db: "admin"
          name: "userAdminAnyDatabase"
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 300m
                  memory: 400M
                limits:
                  cpu: 500m
                  memory: 600M
            - name: "mongod"
              resources:
                requests:
                  cpu: 300m
                  memory: 400M
                limits:
                  cpu: 500m
                  memory: 600M
