apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: react
        image: ${REGISTRY_NAME}/knowzone-frontend:${VERSION}
        resources:
          requests:
            memory: "512Mi"
            cpu: "600m"
          limits:
            memory: "768Mi"
            cpu: "800m"
        env:
        - name: REACT_APP_KNOWZONE_FE_URI
          value: ${FRONTEND_URL}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ${FRONTEND_LB_PREFIX}
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: frontend
