name: Build and deploy to AKS

on: workflow_dispatch

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  VERSION: ${{ github.sha }}
  FRONTEND_LB_PREFIX: ${{ secrets.FRONTEND_LB_PREFIX }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build . -f infra/Dockerfile.web -t ${REGISTRY_NAME}/knowzone-frontend:${{ github.sha }}
        docker push ${REGISTRY_NAME}/knowzone-frontend:${{ github.sha }}

    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
      id: login

    - name: Edit template manifests
      run: |
        envsubst < infra/k8s-manifests/frontend-template.yaml > infra/k8s-manifests/frontend.yaml


    - uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          infra/k8s-manifests/frontend.yaml
